package Main;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author Diego Prada
 */
public class AdministratorPage extends javax.swing.JFrame {
    
  public DatabaseConnect hospitalDB;
    /**
     * 
     * Creates new form AdministratorPage
     */
    public AdministratorPage() {
        hospitalDB = new DatabaseConnect();
        ImageIcon img = new ImageIcon("Picon.png");
        setIconImage(img.getImage());
        initComponents();
        updateLists();
    }
    
    
    
    private void updateLists(){

        ddDOCTORSELECTOR.removeAllItems();
        ddPATIENTSELECTOR.removeAllItems();
        ddINSURANCEPSELECTOR.removeAllItems();
        
        String temp = "";
      try{ 
          Statement stm = hospitalDB.database.createStatement();
          String sql = "Select ID,FirstName, LastName from doctor order by LastName";
          ResultSet rs = stm.executeQuery(sql);
          while(rs.next()){
              temp = rs.getString("ID")+" - "+ rs.getString("LastName")+" "+rs.getString("FirstName");
              ddDOCTORSELECTOR.addItem(temp);
          }
         
         sql = "Select ID,FirstName,LastName from patient order by LastName";
         rs = stm.executeQuery(sql);
         while(rs.next()){
             temp = rs.getString("ID")+" - "+rs.getString("LastName")+" "+rs.getString("FirstName");
             ddPATIENTSELECTOR.addItem(temp);
         }
        
          sql = "Select InsuranceID,ProviderName from insuranceprovider order by ProviderName";
        rs = stm.executeQuery(sql);
         while(rs.next()){
            temp = rs.getString("InsuranceID")+" - "+ rs.getString("ProviderName");
             ddINSURANCEPSELECTOR.addItem(temp);
         }
      
      }catch(Exception e){
          System.out.println(e.getMessage());
      }
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCLOSE = new javax.swing.JButton();
        ddDOCTORSELECTOR = new javax.swing.JComboBox<>();
        ddINSURANCEPSELECTOR = new javax.swing.JComboBox<>();
        btNEWDOCTOR = new javax.swing.JButton();
        btNEWINSURANCEP = new javax.swing.JButton();
        btNEWPATIENT = new javax.swing.JButton();
        ddPATIENTSELECTOR = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btREFRESH = new javax.swing.JButton();
        btNewBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Page");
        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(690, 420));
        setPreferredSize(new java.awt.Dimension(690, 420));
        setResizable(false);

        btCLOSE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCLOSE.setText("CLOSE");
        btCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCLOSEActionPerformed(evt);
            }
        });

        ddDOCTORSELECTOR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ddDOCTORSELECTOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddDOCTORSELECTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddDOCTORSELECTORActionPerformed(evt);
            }
        });

        ddINSURANCEPSELECTOR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ddINSURANCEPSELECTOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddINSURANCEPSELECTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddINSURANCEPSELECTORActionPerformed(evt);
            }
        });

        btNEWDOCTOR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btNEWDOCTOR.setText("New Doctor");
        btNEWDOCTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNEWDOCTORActionPerformed(evt);
            }
        });

        btNEWINSURANCEP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btNEWINSURANCEP.setText("New Insurance Provider");
        btNEWINSURANCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNEWINSURANCEPActionPerformed(evt);
            }
        });

        btNEWPATIENT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btNEWPATIENT.setText("New Patient");
        btNEWPATIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNEWPATIENTActionPerformed(evt);
            }
        });

        ddPATIENTSELECTOR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ddPATIENTSELECTOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddPATIENTSELECTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddPATIENTSELECTORActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Doctors");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Patients");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Insurance Providers");

        btREFRESH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btREFRESH.setText("UPDATE");
        btREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btREFRESHActionPerformed(evt);
            }
        });

        btNewBill.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btNewBill.setText("New Bill");
        btNewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCLOSE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ddINSURANCEPSELECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ddDOCTORSELECTOR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ddPATIENTSELECTOR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btREFRESH)))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btNewBill, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNEWDOCTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btNEWPATIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(btNEWINSURANCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddDOCTORSELECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddPATIENTSELECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btREFRESH))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddINSURANCEPSELECTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNEWDOCTOR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNEWINSURANCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNEWPATIENT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCLOSE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btNewBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddDOCTORSELECTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddDOCTORSELECTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddDOCTORSELECTORActionPerformed

    private void ddINSURANCEPSELECTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddINSURANCEPSELECTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddINSURANCEPSELECTORActionPerformed

    private void ddPATIENTSELECTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddPATIENTSELECTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddPATIENTSELECTORActionPerformed

    private void btCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCLOSEActionPerformed

        this.dispose();
       
        
    }//GEN-LAST:event_btCLOSEActionPerformed

    private void btNEWDOCTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNEWDOCTORActionPerformed
       
        DoctorSetup newdoc = new DoctorSetup();
        newdoc.show();
    }//GEN-LAST:event_btNEWDOCTORActionPerformed

    private void btREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btREFRESHActionPerformed
        // TODO add your handling code here:
        updateLists();
    }//GEN-LAST:event_btREFRESHActionPerformed

    private void btNEWPATIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNEWPATIENTActionPerformed
        // TODO add your handling code here:
        PatientSetup newpat = new PatientSetup();
        newpat.show();
    }//GEN-LAST:event_btNEWPATIENTActionPerformed

    private void btNEWINSURANCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNEWINSURANCEPActionPerformed
        // TODO add your handling code here:
        InsurancePSetup newip = new InsurancePSetup();
        newip.show();
    }//GEN-LAST:event_btNEWINSURANCEPActionPerformed

    private void btNewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewBillActionPerformed
        // TODO add your handling code here:
        BillSetup bs = new BillSetup();
        bs.show();
    }//GEN-LAST:event_btNewBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCLOSE;
    private javax.swing.JButton btNEWDOCTOR;
    private javax.swing.JButton btNEWINSURANCEP;
    private javax.swing.JButton btNEWPATIENT;
    private javax.swing.JButton btNewBill;
    private javax.swing.JButton btREFRESH;
    private javax.swing.JComboBox<String> ddDOCTORSELECTOR;
    private javax.swing.JComboBox<String> ddINSURANCEPSELECTOR;
    private javax.swing.JComboBox<String> ddPATIENTSELECTOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
