/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class BillSetup extends javax.swing.JFrame {
    
    private DatabaseConnect hospitalDB = new DatabaseConnect();
    private static float coverage = 0;
    private static float billedAmount = 0;
    private static float amountPaid = 0;
    private String patID,inID ="";
    

    /**
     * Creates new form BillSetup
     */
    public BillSetup() {
        ImageIcon img = new ImageIcon("Picon.png");
        setIconImage(img.getImage());
        initComponents();
        updateLists();
    }
    
    
    
   private void updateLists(){

        ddPatient.removeAllItems();
        String temp = "";
      try{ 
          Statement stm = hospitalDB.database.createStatement();
          String sql = "Select ID,FirstName, LastName from patient order by LastName";
          ResultSet rs = stm.executeQuery(sql);
          while(rs.next()){
              temp = rs.getString("ID")+" - "+ rs.getString("LastName")+" "+rs.getString("FirstName");
              ddPatient.addItem(temp);
          }
          
      }catch(Exception e){
          System.out.println(e.getMessage());
      } 
    }
   
   void update(){
       
       coverage = 0;
       try{
       String temp = ddPatient.getSelectedItem()+"";
       temp = temp.substring(0,6);
       patID = temp;
       String sql = "select patient.insuranceID,coverage from patient inner join insuranceprovider on patient.InsuranceID = insuranceprovider.InsuranceID where id =" + temp;
       Statement stm = hospitalDB.database.createStatement();
       ResultSet rs = stm.executeQuery(sql);
       
       while(rs.next()){
           coverage = rs.getFloat("coverage");
           lbCoverage.setText(coverage+"");
           inID = rs.getString("insuranceID");
       }
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
       
      try{
       amountPaid = Float.valueOf(tfAmountPaid.getText());
       billedAmount = Float.valueOf(tfBillAmount.getText());
       }catch(Exception e){
       } 
      
       float amount = billedAmount - coverage - amountPaid;
       if(amount<0)
        lbAmountOwed.setText("0.0");
       else
           lbAmountOwed.setText(amount+"");
       
   }
   
   
    void createBill(){
        try{
       String sql = "INSERT INTO bill(patientID,InsuranceID,BilledAmount,TotalAmountOwed,AmountPaid)"
               + " VALUES("+patID+", "+inID+", "+billedAmount+", "+lbAmountOwed.getText()+", "+amountPaid+")";
       PreparedStatement stm = hospitalDB.database.prepareStatement(sql);
       stm.executeUpdate();
       JOptionPane.showMessageDialog(this,"Bill created successfuly!");
       dispose();
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this,"Something went wrong, Please try again using decimal point!");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btClose = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        ddPatient = new javax.swing.JComboBox<>();
        tfBillAmount = new javax.swing.JTextField();
        tfAmountPaid = new javax.swing.JTextField();
        lbCoverage = new javax.swing.JLabel();
        lbAmountOwed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbCoverage1 = new javax.swing.JLabel();
        lbCoverage2 = new javax.swing.JLabel();
        lbCoverage3 = new javax.swing.JLabel();
        lbCoverage4 = new javax.swing.JLabel();
        lbCoverage5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Bill");

        btClose.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        btCreate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btCreate.setText("Create");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });

        ddPatient.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ddPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddPatientActionPerformed(evt);
            }
        });

        tfBillAmount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfBillAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBillAmountActionPerformed(evt);
            }
        });

        tfAmountPaid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfAmountPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountPaidActionPerformed(evt);
            }
        });

        lbCoverage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage.setText("Insurance Coverage");

        lbAmountOwed.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbAmountOwed.setText("Amount Owed");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("BILL");

        lbCoverage1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage1.setText("Total Amount billed");

        lbCoverage2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage2.setText("Patient");

        lbCoverage3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage3.setText("Insurance Coverage");

        lbCoverage4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage4.setText("Total Amount Paid");

        lbCoverage5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbCoverage5.setText("Total Amount Owed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCreate)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCoverage2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(lbCoverage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCoverage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCoverage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCoverage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAmountOwed)
                            .addComponent(ddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbCoverage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(tfAmountPaid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfBillAmount, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCoverage2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCoverage)
                    .addComponent(lbCoverage3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCoverage1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCoverage4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAmountOwed)
                    .addComponent(lbCoverage5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(btCreate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed

        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void ddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddPatientActionPerformed
        update();
    }//GEN-LAST:event_ddPatientActionPerformed

    private void tfBillAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBillAmountActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_tfBillAmountActionPerformed

    private void tfAmountPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountPaidActionPerformed
        // TODO add your handling code here:
         update();
    }//GEN-LAST:event_tfAmountPaidActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        // TODO add your handling code here:
        createBill();
    }//GEN-LAST:event_btCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btCreate;
    private javax.swing.JComboBox<String> ddPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAmountOwed;
    private javax.swing.JLabel lbCoverage;
    private javax.swing.JLabel lbCoverage1;
    private javax.swing.JLabel lbCoverage2;
    private javax.swing.JLabel lbCoverage3;
    private javax.swing.JLabel lbCoverage4;
    private javax.swing.JLabel lbCoverage5;
    private javax.swing.JTextField tfAmountPaid;
    private javax.swing.JTextField tfBillAmount;
    // End of variables declaration//GEN-END:variables
}
