/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.*;
import javax.swing.ImageIcon;

/**
 *
 * @author diego
 */
public class PatientPage extends javax.swing.JFrame {
    
    private DatabaseConnect db = new DatabaseConnect();
    private static String patientID;
    private static String mdocID;

    /**
     * Creates new form PatientPage
     */
    public PatientPage(String patientID) {
        ImageIcon img = new ImageIcon("Picon.png");
        setIconImage(img.getImage());
        initComponents();
        this.patientID  = patientID;
        setLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogOut = new javax.swing.JButton();
        btRecords = new javax.swing.JButton();
        btAppointments = new javax.swing.JButton();
        pic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbProfile = new javax.swing.JTextArea();
        btCapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Page");

        btLogOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btLogOut.setText("Log Out");
        btLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogOutActionPerformed(evt);
            }
        });

        btRecords.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btRecords.setText("Records");
        btRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecordsActionPerformed(evt);
            }
        });

        btAppointments.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btAppointments.setText("View Appointments");
        btAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAppointmentsActionPerformed(evt);
            }
        });

        pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient.png"))); // NOI18N

        lbProfile.setEditable(false);
        lbProfile.setBackground(new java.awt.Color(204, 204, 204));
        lbProfile.setColumns(20);
        lbProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbProfile.setRows(3);
        jScrollPane1.setViewportView(lbProfile);

        btCapp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCapp.setText("Create Appointment");
        btCapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btLogOut)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCapp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btRecords)
                .addGap(16, 16, 16)
                .addComponent(btCapp)
                .addGap(18, 18, 18)
                .addComponent(btAppointments)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogOutActionPerformed
        
        Login log = new Login();
        log.show();
        dispose();
    }//GEN-LAST:event_btLogOutActionPerformed

    private void btRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecordsActionPerformed
        RecordsPage rp = new RecordsPage(patientID);
        rp.show();
    }//GEN-LAST:event_btRecordsActionPerformed

    private void btCappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCappActionPerformed
        // TODO add your handling code here:
        AppointmentSetup ast = new AppointmentSetup(patientID,mdocID);
        ast.show();
    }//GEN-LAST:event_btCappActionPerformed

    private void btAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAppointmentsActionPerformed
        // TODO add your handling code here:
        ViewApp na = new ViewApp(patientID);
        na.show();
    }//GEN-LAST:event_btAppointmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPage(patientID).setVisible(true);
            }
        });
    }
    
    
    // Automatically updates the label with the information of the patient.
    private void setLabel(){
        lbProfile.setText("");
        try{
            String sql = "Select FirstName,LastName,BirthDate,Phone,DoctorID From patient where id = "+patientID;
            Statement stm = db.database.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                String name = rs.getString("FirstName")+" "+rs.getString("LastName");
                String dob = rs.getString("BirthDate");
                String pnum  = rs.getString("Phone");
                lbProfile.setText(name+"\n"+dob+"\n"+pnum);
                mdocID = rs.getString("DoctorID");
            }
            
        }catch(Exception e){
            
            System.out.println("Patient label: "+e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAppointments;
    private javax.swing.JButton btCapp;
    private javax.swing.JButton btLogOut;
    private javax.swing.JButton btRecords;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lbProfile;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
